baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[params]
  description = "What a beautiful day!"
  footer = "I'm not *that* bad!"

[menus]
  [[menus.main]]
    pre = "Visit"
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    pre = "Read"
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    pre = "Explore"
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
